new: added docker-publish.yml

diff --git a/.github/workflows/docker-publish.yml b/.github/workflows/docker-publish.yml
--- a/.github/workflows/docker-publish.yml
+++ b/.github/workflows/docker-publish.yml
@@ -6,15 +6,38 @@ on:
     #    - main
 
 jobs:
-    build:
+    docker:
         runs-on: ubuntu-latest
         steps:
             - name: Checkout Code
               uses: actions/checkout@v4
 
-            - name: Building Docker image
+            - name: Docker Hub Login
+              uses: docker/login-action@v3
+              with:
+                username: ${{secrets.DOCKER_USERNAME}}
+                password: ${{secrets.DOCKER_TOKEN}}
+            
+            - name: Set up Docker Buildx
+              uses: docker/setup-buildx-action@v3    
+
+            - name: Build and Push Docker Image
               uses: docker/build-push-action@v6
               with:
                 context: .
                 push: true
-                tags: user/app:latest
+                tags: |
+                  ${{ secrets.DOCKERHUB_USERNAME }}/demo-app:latest
+                  ${{ secrets.DOCKERHUB_USERNAME }}/demo-app:${{ github.sha }}
+
+            - name: Run container
+              run: |
+                docker run -d --name demo-app -p 3000:3000 \
+                ${{ secrets.DOCKERHUB_USERNAME }}/demo-app:latest
+ 
+                sleep 5
+ 
+                docker ps | grep demo-app || { echo "Container failed to start!"; exit 1; }
+ 
+            - name: Stop container
+              run: docker stop demo-app && docker rm demo-app      
